### ISSUE TITLE
Library headers are clashing with local headers

### ISSUE THREAD

**Issue by axalon900** [litehtml/litehtml#102]
Hi, I include litehtml as a subdirectory in my CMake project and the fact that litehtml's (and in this case, gumbo's) headers are in the root folder of their include directory is causing conflicts with my project's headers. Namely:

```cpp
fatal error: non-portable path to file '"error.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include "Error.h"
         ^~~~~~~~~
         "error.h"
```

It's confusing my `Error.h` with gumbo's `error.h` because gumbo's header is accessible as `#include <error.h>` as defined in the CMakeLists, so #include "Error.h" will hit both my local header and litehtml's *system* header. This would not happen if the public header path instead were `#include <gumbo/error.h>` or something more reasonable. I think this is done when you *install* litehtml, but if you're including it as part of your build like I am this problem still exists. 

Thanks!

**Comment by tordex** [comment]
I've merged your pull request. Thank you.
