### ISSUE TITLE
Which version of C++ ISO does litehtml expect?

### ISSUE THREAD

**Issue by deniskak** [litehtml/litehtml#107]
It's a rather interesting project. However, I've got a question based on the description of the library: "litehtml is compatible with any platform suported by C++..". Does this imply C++03, C++11, 14 or 17? I think it would be good to add this detail to the front page. Thanks.

**Comment by tordex** [comment]
С++11

**Comment by deniskak** [comment]
@tordex thx, any chance you can share high-level details of specific c++11 features used? I'm looking for something that would work with c++03 and may fork if it's not too much pain to port to c++03.

PS I'd can help improving English in some of the documentation if you're interested.

**Comment by tordex** [comment]
> any chance you can share high-level details of specific c++11 features used?
Here the list (may be incomplete):
auto keyword
Range-based for()
Initializer lists
std::shared_ptr
lambdas
move data

> PS I'd can help improving English in some of the documentation if you're interested.
I would be happy for any help

**Comment by deniskak** [comment]
@tordex thx. I did a bit quick code search and it may be feasible to backport a lot of this to C++03 and Boost. 

Re language it's mainly changes to https://github.com/litehtml/litehtml/wiki/document_container I was thinking of. Should I fork to edit this page or can you give me permissions to edit and submit it as a pull request or something of that sort?

**Comment by tordex** [comment]
Fork/pull request is preferred way. Thank you.
