### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by ibinshoid** [litehtml/litehtml#113]
In many html files there is overlapping text if the text is in a table.
i have attached a screenshot and a sample html file

![Bildschirmfoto_2019-11-03_10-25-21](https://user-images.githubusercontent.com/16139662/68083066-add1db00-fe24-11e9-8312-9b26054814b6.png)

[samplehtml.txt](https://github.com/litehtml/litehtml/files/3801394/samplehtml.txt)

**Comment by tordex** [comment]
Do you use custom container class? Usually these overlaps appear if `litehtml::document_container` returns incorrect text width.

**Comment by ibinshoid** [comment]
This appears with the latest litebrowser-linux + the latest litehtml(90555f1) and also with the claws-mail litehtml-plugin 3.17.4. I've also comiled the plugin with litehtml 90555f1 and got the same result.
this mostly happens when html tables are used for layout.
I'm using openSuse 15.0
