### ISSUE TITLE
How to build on Linux?

### ISSUE THREAD

**Issue by tig** [litehtml/litehtml#122]
The instructions for building on Linux using `LiteHtmlSharp` don't work:

```
cd LiteHtmlLib
sh build.sh
```

I'm not familiar enough with building on Linux to figure this out myself. Can you give me the steps to build? I've got cmake installed but I'm not sure what `cmake` incantation to use. I noted the `premake5.lua` file but lua (5.1) barfs with:

```
stack traceback:
	premake5.lua:1: in main chunk
	[C]: in ?
```

Help please.

**Comment by tordex** [comment]
It is simple:
```
https://github.com/litehtml/litehtml.git
cd litehtml/
mkdir build
cd build
cmake ../
make
```
Optional `make install`

**Comment by tig** [comment]
Thanks. I got it to build. 

However, when I run `sudo make install` the lib gets put into `/usr/local/lib/liblitehtml.a`

On my system (Ubuntu 18.04) `LD_DEBUG` shows the loader only wants to look in `/usr/lib` (and other places, but not `/usr/local/lib`. Do you know how I fix either `make install` or the config (hopefully programmatically because I sure would like to build an installer)...

**Comment by tordex** [comment]
Make symlink in `/usr/lib` or just copy files.
