### ISSUE TITLE
/usr/bin/ld: liblitehtml.a(document.cpp.o): in function `void 

### ISSUE THREAD

**Issue by TechComet** [litehtml/litehtml#132]
[100%] Linking CXX executable litehtml_tests
/usr/bin/ld: liblitehtml.a(document.cpp.o): in function `void __gnu_cxx::new_allocator<litehtml::el_li>::construct<litehtml::el_li, std::shared_ptr<litehtml::document>&>(litehtml::el_li*, std::shared_ptr<litehtml::document>&)':
document.cpp:(.text._ZN9__gnu_cxx13new_allocatorIN8litehtml5el_liEE9constructIS2_JRSt10shared_ptrINS1_8documentEEEEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorIN8litehtml5el_liEE9constructIS2_JRSt10shared_ptrINS1_8documentEEEEEvPT_DpOT0_]+0x43): undefined reference to `litehtml::el_li::el_li(std::shared_ptr<litehtml::document> const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/litehtml_tests.dir/build.make:215: litehtml_tests] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/litehtml_tests.dir/all] Error 2
make: *** [Makefile:161: all] Error 2

**Comment by tordex** [comment]
Merged pull request #131 to fix this bug
