### ISSUE TITLE
vcpkg support?

### ISSUE THREAD

**Issue by linuxaged** [litehtml/litehtml#133]
The `gumbo` lib is in vcpkg ports,  building and integration would be quite simple if litehtml supports vcpkg

**Comment by rioki** [comment]
I tried to write a port file and ran into some issues.

- vcpkg want stable versions, tag v0.5 is kind of out of date and that CMakeLists.txt does not do any sensible install
- litehtml does not export any symbols in windows
- default CMakeLists.txt uses it's own version of gumbo, using that version of vcpkg is strongly encouraged.

My work so far: https://github.com/rioki/vcpkg/commit/32e970a3013ccdca25d93083cb955a389625e08c
