### ISSUE TITLE
Sharing CSS?

### ISSUE THREAD

**Issue by crazydef** [litehtml/litehtml#139]
Hi,

Is it possible to pre-load styles from a CSS file and share those styles between multiple documents.

And following on from that, how can I apply a different set of styles to a document at runtime?  (I.e., if I wanted to switch between light and dark themes, for example?)

**Comment by tordex** [comment]
Yes, it is possible. Look at ``createFromString`` function:
``` C++
static litehtml::document::ptr createFromString(const tchar_t* str, litehtml::document_container* objPainter, litehtml::context* ctx, litehtml::css* user_styles = 0);
```
You can use both `user_styles` and `ctx` parameters. Both are preloaded css.
