### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by NQUARE** [litehtml/litehtml#145]
Hello everybody!
When I try to build litehtml using mingw32-make I get the following error:
`In file included from S:\litehtml-0.5\src\document.cpp:28:
S:\litehtml-0.5\src\document.cpp: In member function 'void litehtml::document::create_node(GumboNode*, litehtml::elements_vector&)':
S:\litehtml-0.5\src\utf8_strings.h:45:34: error: conversion from 'litehtml::utf8_to_wchar' to non-scalar type 'litehtml::tstring' {aka 'std::__cxx11::basic_string<wchar_t>'} requested
 #define litehtml_from_utf8(str)  utf8_to_wchar(str)
                                  ^~~~~~~~~~~~~~~~~~
S:\litehtml-0.5\src\document.cpp:750:18: note: in expansion of macro 'litehtml_from_utf8'
    tstring str = litehtml_from_utf8(node->v.text.text);
                  ^~~~~~~~~~~~~~~~~~
mingw32-make[2]: *** [CMakeFiles\litehtml.dir\build.make:152: CMakeFiles/litehtml.dir/src/document.cpp.obj] Error 1
mingw32-make[1]: *** [CMakeFiles\Makefile2:114: CMakeFiles/litehtml.dir/all] Error 2
mingw32-make: *** [Makefile:102: all] Error 2`
I really hope that someone will help me.

**Comment by Pevernow** [comment]
I have the same problem with mingw32-make.

Could you help me?
