### ISSUE TITLE
Google, yahoo, etc don't render correctly

### ISSUE THREAD

**Issue by Unity123** [litehtml/litehtml#146]
No common webpages render correctly. Even my own webpage, which is hacked together and is really ugly, still doesn't render correctly (no form elements). Please try and make your web browser engine function as a web browser engine, litehtml!
My website: [cgod.ml](http://cgod.ml)

**Comment by Unity123** [comment]
@xtreme800 ytho

**Comment by xtreme8000** [comment]
> @xtreme800 ytho

Did you even read the section(s) in [README.md](https://github.com/litehtml/litehtml#where-litehtml-can-be-used)?

*Quote:*
> but using it as a full-featured HTML engine is not recommended

It is quite clear that this project is not intended to render heavy websites, it's mostly for HTML directly tailored to it.

**Comment by Unity123** [comment]
I _would_ not use it, but I think it has the best shot at running on 64 megabytes of ram, and that's the reason I chose it.
