### ISSUE TITLE
example of rendering in a BGRA buffer

### ISSUE THREAD

**Issue by vtorri** [litehtml/litehtml#157]
everything in the topic : 

is there a simple example of rendering in a BGRA buffer somewhere ?

thank you

Vincent Torri

**Comment by zcream** [comment]
I have the same question - a simple example where we can supply an image buffer of a certain size, and lite html would render a supplied html string to it - would be very helpful.

**Comment by mgambrell** [comment]
The cairo container does this. Good luck getting cairo, pixman, and truetype to build.
You could make a container with stb_truetype and stb_image, although I don't know an equivalently slim rendering library. Hand-crafting blitters would not be an insane proposition for this.
