### ISSUE TITLE
litehtml incorrectly uses local-aware functions (at least on Linux)

### ISSUE THREAD

**Issue by g4mba5** [litehtml/litehtml#174]
Hi,

I'm currently using `litehtml` to create an HTML view control for the [Gambas](https://gitlab.com/gambas/gambas) language. 

The `os_types.h` file has the following `#define`:
```
#define t_strcasecmp		strcasecmp
#define t_strncasecmp		strncasecmp
#define t_strtod		strtod
#define t_tolower		tolower
#define t_isdigit		isdigit
```
But these functions are locale-aware, whereas the parsing must not be.

For example, on a French system, the `litehtml::css_length::fromString` function fails to read decimal numbers in CSS files, because the French decimal separator is the comma, not the point.

Another example: in Turkish, `i` and `I` are not the same letter with a different case, so some non case-sensitive string comparisons will fail.

As `litehtml` packaging is broken, at least on Ubuntu, I embedded the source code of `litehtml` and `gumbo`, and so could patch the code.

To do that I redirected these functions on internal Gambas interpreter functions, so I can't provide a patch suited to `litehtml` at the moment. The main difficulty is rewriting `strtod`.

Anyway, congratulations for having wrote this library. Gambas will soon be able to display HTML with Qt4, Qt5, GTK+2 and GTK+3 without having relying on Webkit that eats hundreds of megabytes.

**Comment by g4mba5** [comment]
I provided two pull request to fix the bug. One for `strtod`, another one for the other functions.

**Comment by tordex** [comment]
Unfortunately your pull request for `strtod` brakes the parsing. So I've add other implementation of `strtod`.
Other pull request is merged with some refactoring.
Thank you!

**Comment by g4mba5** [comment]
No problem. I had to have a quick implementation so that I could use the library. It's better to have a full strtod() implementation to respect the CSS standard as much as possible.

By the way, I'm curious about what my strtod() breaks in the parsing except that point.

And I hope one day one POSIX committee member or one C-library developer becomes aware of the problem of local-aware string functions...

**Comment by Dushistov** [comment]
@g4mba5 

There is [std::from_chars](https://en.cppreference.com/w/cpp/utility/from_chars) , it is locale in depend
and should be faster then `strtod`. But it is from C++17.

**Comment by tordex** [comment]
Yes, I know about std::from_chars, but I'm not ready to move into C++17 :(
