### ISSUE TITLE
'em' and 'rem' sizes are incorrectly computed

### ISSUE THREAD

**Issue by g4mba5** [litehtml/litehtml#175]
In `document.cpp`, we have:
```
int litehtml::document::cvt_units( css_length& val, int fontSize, int size ) const
{
...
	case css_units_em:
		ret = round_f(val.val() * fontSize);
		val.set_value((float) ret, css_units_px);
		break;
```
This is incorrect, because `fontSize` is the size of the font in points, and the function return pixels. `fontSize` must be converted to pixels.

**Comment by g4mba5** [comment]
Same problem with `rem`.

**Comment by tordex** [comment]
Your are right, ```fontSize``` must be in pixels. And if you'll find all references to ```cvt_units```, you'll see the ```fontSize``` is passed as size in pixels.

**Comment by g4mba5** [comment]
OK, I see my mistake. The font size in `document_container::create_font` is in pixels, not in points. You can send my merge request to the trash then.
