### ISSUE TITLE
Problem with a protected method

### ISSUE THREAD

**Issue by bigfatbrowncat** [litehtml/litehtml#20]
An architecture problem.
I'm trying to create a custom tag that lays out elements inside. I want to subclass <code>el_div</code> and add some features (I want to make a scrollable <code>div</code> block).

1. I can't find any <code>el_div.h</code>, but that isn't a problem - <code>el_div</code> is very simple, I can subclass from <code>html_tag</code> directly.
2. I'm trying to create <code>place_element()</code> implementation to modify each sub-element's <code>m_pos</code>. But I can't access <code>el->m_pos</code> from my class.

What should I do? How to accomplish this in a right way?

**Comment by bigfatbrowncat** [comment]
Another problem: when I implemented <code>document_container::create_element()</code>, I've found that in <code>tag_name</code> argument this function receives not only the tag name itself ("vscroll" in my case), but the complete tag
```
<vscroll position="100pt">
```
Is that a bug?

**Comment by tordex** [comment]
> I can't find any el_div.h, but that isn't a problem - el_div is very simple, I can subclass from html_tag directly.

```el_div.h``` is in ```src``` folder. It is not included by ```include/litehtml.h```.

> I'm trying to create place_element() implementation to modify each sub-element's m_pos. But I can't access el->m_pos from my class.

OK, I've added element::get_position to get access to the m_pos in ed641bebe0b5758bf3e8b30c2533533d82fc8f56

> Another problem: when I implemented document_container::create_element(), I've found that in tag_name argument this function receives not only the tag name itself ("vscroll" in my case), but the complete tag

This is a bug, I've fixed it in ec71167d0a7718c7bb1a2e9b821d00406856ba86

**Comment by bigfatbrowncat** [comment]
Ok, thank you. I'll update your code in my project.
