### ISSUE TITLE
About animated GIF

### ISSUE THREAD

**Issue by crskycode** [litehtml/litehtml#205]
Add a state to `background_paint` to draw animated GIF for each element.

**Comment by mgambrell** [comment]
Seems like this is the container's job.. you load the image, you know that it's an animated gif, you know what you think the current time is, so you can calculate which frame from the animated gif to use in draw_background(). I can't even see how litehtml would be able to help you here.

**Comment by crskycode** [comment]
I know, but there will need a variable to store the state of the image, like a userdata field.

**Comment by mgambrell** [comment]
You don't get the element when you're instructed to draw_background(), do you? That's supposed to be stateless

**Comment by crskycode** [comment]
You mean start timing from the moment the image loads? All elements referencing the same image will have the same frame.

**Comment by mgambrell** [comment]
Yes, that's what I mean. Yes, that would happen. Is the timing of GIFs really a specified feature? What other t=0 could the specifications possibly specify?

**Comment by crskycode** [comment]
Well, I want to start timing from the moment the element is created. Anyway, thanks for your reply.
