### ISSUE TITLE
Incorrect menu width on old unicode.org

### ISSUE THREAD

**Issue by stasoid** [litehtml/litehtml#208]
Page: [old unicode.org](https://web.archive.org/web/20110101155107/http://www.unicode.org/).
Problem: left menu is too wide.
Minirepro:
```html
<table width=200px border=1>
<tr>
  <td>
    <div style="width:100%"> aaa
  <td>
    bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb
```
Is rendered like this:
![image](https://user-images.githubusercontent.com/2577509/175833794-2351f91c-0221-4850-8276-63a941790122.png)
Should be:
![image](https://user-images.githubusercontent.com/2577509/175833816-14163f3e-087a-44eb-ae85-abebfa9e5013.png)
Culprit: `width:100%`

**Comment by tordex** [comment]
Fixed in the branch refactor.
