### ISSUE TITLE
Text-align: justify does not work

### ISSUE THREAD

**Issue by MXADD** [litehtml/litehtml#214]
Doing this:
`<p style="text-align: justify;">some larger block of text</p>`
Does not justify text block, it seems that only right/left/center work correctly, justify is just ignored, any chance to get this ?

The minimal support could just distribute remaining space in line box to the whitespaces, no need to go in the 'adjust font kerning' stuff.

**Comment by MXADD** [comment]
For now I'v created crude workaround for the problem as I needed justification badly, attached patch file, meybe someone will come up with something better...
[justify.txt](https://github.com/litehtml/litehtml/files/9746555/justify.txt)

**Comment by tordex** [comment]
Thank you for patch. I've added it into 31cb197 with small changes.
