### ISSUE TITLE
Remove wchar support?

### ISSUE THREAD

**Issue by stasoid** [litehtml/litehtml#217]
I would like to remove wchar support from litehtml. My issue with it is that it adds unnecessary complexity to litehtml. We now have not two, but three entities: char, wchar_t and tchar_t. UTF-16 is a Windows-specific problem, and I don't like how it "contaminates" a cross-platform library. I'd rather let Windows clients deal with the conversions to/from UTF-16, and keep litehtml interface and internals pure UTF-8.

I know wchar support exists for a reason, but it was added long time ago, maybe you changed your mind? Esp. considering that it is now obvious that UTF-8 is the "one true way".

What do you think?

**Comment by tordex** [comment]
You are right support of wchar adds unnecessary complexity to litehtml, so let's remove it.

**Comment by tordex** [comment]
Good job @stasoid! Thank you!

**Comment by ryandesign** [comment]
[The wiki](https://github.com/litehtml/litehtml/wiki#what-encodings-are-supported-by-litehtml) still says "litehtml works with wchar_t (Windows) or utf-8 strings". Can that be corrected?
