### ISSUE TITLE
Proposal to merge litehtml::context into document_container

### ISSUE THREAD

**Issue by stasoid** [litehtml/litehtml#219]
I propose to remove litehtml::context and add 2 methods to document_container:
```cpp
virtual string get_master_css() { return litehtml::master_css; }
virtual string get_user_css() { return ""; }
```
Looks like document_container alone is enough to supply all the environment needed.
Or, if you still want to pass master/user css separately from document_container, I would like to pass them just as strings. I don't see any compelling reason why they should be preparsed before passing to document::createFromString.

Also, do we really need master.css as a CSS file? The lack of #include_as_string directive in C++ makes it awkward to deal with. Why not just have master_css.h like this:
```cpp
namespace litehtml{ const char* master_css = R"##(


/* contents of master.css */


)##"; }
```
This way, we can provide get_master_css() implementation without generating any files or making client deal with LoadResource.
Thanks to C++ raw strings master_css.h can be updated just as easily as master.css.

I would also like to create document_container.h/cpp. I feel like this class is important enough to have dedicated files.

**Comment by tordex** [comment]
> I don't see any compelling reason why they should be preparsed before passing to document::createFromString.

This is the main idea of ```litehtml::context``` and "user css". We have two pre-parsed ```litehtml::css``` object. The master css is applied first and supplies the basic tags definitions, the user css is applied at the end. Why pre-parsed? CSS parsing is heavy operation, but master/user css don't change frequently. So we cat some time on the parsing these CSS's.

Anyway, as I see now, the class ```litehtml::context``` is redundant now and can be removed. So the ```createFromString``` method would be like:
```C++
litehtml::document::createFromString( const char* str, litehtml::document_container* objPainter, litehtml::css* master_styles, litehtml::css* user_styles )
```

> if you still want to pass master/user css separately from document_container, I would like to pass them just as strings.

So we can just overwrite createFromString with strings, parse both CSS's and call ```createFromString``` with ```litehtml::css``` objects:
```C++
litehtml::document::createFromString( const char* str, litehtml::document_container* objPainter, const char* master_styles, const char* user_styles )
```
Of cause we should control ownership of ```litehtml::css``` objects with smart pointers in this case.

> Also, do we really need master.css as a CSS file? The lack of #include_as_string directive in C++ makes it awkward to deal with.

Actually master.css is just for example in the library, or something like reference. Library gets *text* of the master.css via argument of ```document::createFromString``` function. No matter how an application implements storing master css text.

Anyway creating ```master_css.h``` maybe useful. But and end application only should use this file.

> I would also like to create document_container.h/cpp. I feel like this class is important enough to have dedicated files.

I agree.

**Comment by stasoid** [comment]
> CSS parsing is heavy operation

I don't think parsing master css can be considered heavy in any of litehtml use cases.
Obviously, parsing master css is not a problem with normal-sized pages. 
So we are talking about the worst-case scenario, displaying a lot of small html snippets, like html tooltips.
This is a rendering test of html "Hello!" with master.css from litehtml on my machine:
```
context.load_master_stylesheet: 171 mks
document::createFromString: 935 mks
doc->render: 23 mks
doc->draw: 4274 mks
```
Note that these are <ins>micro</ins>seconds.
As you can see, the whole rendering takes 5403 mks, and load_master_stylesheet takes 171 mks = 3% of that.
Taking user styles into account doesn't change the situation (so it's gonna be 342 mks, whatever).
Remember, this is the absolute worst scenario, with the tiniest html possible, and I didn't even take into account other additional stuff, like time to display actual tooltip window.

So I still think createFromString overload with litehtml::css* arguments is not necessary.
But I also think it's not worth arguing about, so if I didn't convince you and you still want to keep it, let's keep it.

--------------

> Actually master.css is just for example in the library

I disagree with the treatment of master.css as a second-class citizen. CSS rules in that file are
absolutely necessary to display any html correctly, for example `head{display:none}` or `table{display:table}`, and most of them are [directly specified in html standard](https://html.spec.whatwg.org/multipage/rendering.html#non-replaced-elements).
So master.css is an integral part of html rendering.

> Anyway creating `master_css.h` maybe useful. But and end application only should use this file.

So I think it is only natural for litehtml users to just use the default master.css, and I propose to make it the default argument:
```cpp
document::createFromString( const char* str, litehtml::document_container* objPainter, const char* master_styles = litehtml::master_css, const char* user_styles = "" )
```

Just to be clear: I want to remove master.css and keep only master_css.h because trying to keep them in sync is error prone and confusing.
If you want to keep master.css as a CSS I have an alternative idea of making it a CSS/C++ polyglot, so it can be #included directly, but I prefer the master_css.h solution because it is less hackish.

**Comment by tordex** [comment]
Ok, you convinced me. Let's remove ```litehtml::context``` and pass master/user css to litehtml via argument as strings:
```C++
document::createFromString( const char* str, litehtml::document_container* objPainter, const char* master_styles = litehtml::master_css, const char* user_styles = "" )
```
I like this way, it is more convenient. So master.css should be replaced with master_css.h

PS. 
I've just noticed the litehtml is 10 years old already. There are some legacy ideas there as I see.

**Comment by ryandesign** [comment]
Please don't remove master.css. In my application, that is the file I use; I don't use the generated header file. Some developers may wish to bake the master CSS into their application executable, but I wish to incorporate it into my application in a different manner that is more appropriate for my situation. If you do remove master.css, I can surely modify my build process to convert the header file back into the plain CSS representation I need but it seems wrong to me to make the header file—which is the generated file—the primary source, when the plain CSS file is clearly the source.

If you do make changes to the master CSS file, may I suggest that the term "master" be retired. There has been some effort towards this goal in other open source projects in recent years. Perhaps a term like "default" or "base" could be used instead.

As to why the CSS should be pre-parsed, I certainly prefer that any parsing of the default CSS occur once at application startup time, not every time an HTML document is loaded. I would also want the default CSS representation to be stored in memory just once, not copied into every document. Performance and memory use may not be a problem on your fast modern system, but litehtml is "lite" so I am using it in an application made for systems that are much less capable than your typical desktop PC so fast performance and low memory use is very important to me and I appreciate any efforts undertaken toward optimization.

**Comment by stasoid** [comment]
@ryandesign Can you please explain what is your situation exactly? Because I can't understand why you can't have it inside executable - it's just another string. If this proposal is accepted, you won't have to deal with master.css at all - it will be automatically substituted as the default argument. I am trying to simplify the interface.

**Comment by ryandesign** [comment]
On the platform I'm developing for, it's customary to store text strings, images, sounds, and so forth in a resource database. One reason is so that individual resources can be loaded into and unloaded from memory as needed. For example, at app startup, after my executable code is in memory, I read the default CSS text from the resource database, pass it to `litehtml::context`'s `load_master_stylesheet()`, and then free the memory that the default CSS text occupied. If it were baked into my executable code as a string literal I couldn't free just that text string; it would remain in memory as long as my application is open even though I never need to access it again.

**Comment by stasoid** [comment]
@ryandesign The binary size of the library is ~ 800KB. Dynamic allocations are probably adding several hundred KB on top of that even for simple html files. There is no point in saving 4KB (the size of master.css) of memory in this case.

**Comment by ryandesign** [comment]
If I understand correctly, previously, you would create one global context before creating the first document and have it parse the default CSS. Then, when you create a document, you pass it the HTML string and also a reference to the context. Even if you open ten documents, the default CSS only needed to be parsed once, and the parsed default CSS is only in memory once.

Now, if I understand your proposal correctly, you suggest that there would be no context, and when creating a document, you pass it the HTML string and the default CSS string. If you open ten documents, the default CSS would need to be parsed ten times, and there would be ten copies of it in memory.

If I'm correct in my understanding, then this doesn't seem like an improvement to me. However, I'm a newcomer here and my knowledge of how litehtml works is still rudimentary. It is of course up to the developer to decide how to proceed, and I see that he has merged your PR, so I suppose the matter is closed.
