### ISSUE TITLE
line_height broken 

### ISSUE THREAD

**Issue by mgambrell** [litehtml/litehtml#232]
de4893f0b660e9e8a86a2f3aee13230faa6191f8

this commit broke the line_height concept. Sorry my terminology here will be terrible, I don't understand html and CSS much. At some point (I guess, this commit), the css_properties type's m_line_height member became a css_length. but it is initialized to zero (NOT predefined). Due to that, it won't be fetched from the font metrics (it's thought to be zero precisely). In older versions, the m_line_height was an integer and the predefinedness was handled near where the metrics are fetched. It would be passing `normal` as css_length default_value.

The is_line_height_predefined() and m_lh_predefined are peculiar. They seem sensible when m_line_height was an integer. Now that it's not an integer, I don't think it should exist.

I am proposing to fix these problems as follows:
1. get rid of m_lh_predefined and friends (they arent used)
2. change `m_line_height(0)` to `m_line_height(css_length::predef_value(0))` in css_properties.h

There is one further problem here. This same code I've been talking about.. I'll write it here for reference
`m_line_height = el->get_length_property(_line_height_, true, normal, offset(m_line_height));`
This is instructing the property to be inherited in case it isn't set, I guess. Unfortunately, by the time this is happening (for me), the parent has a well-defined value derived from the font metrics--the WRONG font metrics, for the inherited style. That's because this code is kind of "resolving" it. But the "unresolvedness" needs to propagate as well.

So I propose a third change:
3. add `int m_line_height_resolved` to css_properties (and add a getter)
3b. Revert efforts to use floats for those calculations of m_line_height since while m_line_height can have floats, m_line_height_resolved cannot sensibly.

Also, it would seem that set_line_height and get_line_height should use a css_length (it seems like this was forgotten when it was changed from int).

**Comment by mgambrell** [comment]
2. OK you're right, it didn't matter
3. The line height is the only thing that has this funny behavior.. the m_line_height itself works normally like everything else on the type more or less. the "resolved" value is what's strange, so i think it should have a strange name to get attention "why did this need resolving and what does that mean?"

**Comment by stasoid** [comment]
Enough time has passed, tordex is unlikely to respond. Will you write the PR? If you don't want to, I will do.

**Comment by tordex** [comment]
I'm sorry, I see some issues with line height but my time is very limited now. 
As I see the m_lh_predefined is not used, so it can be removed.
I don't see why we need the "computed" line_height. @mgambrell, please could you post some examples about issues with line height?

**Comment by mgambrell** [comment]
I tried to explain why the computed height is needed (the code believes it has a non-predefined value of zero so it doesn't fetch the height from the font metrics) but perhaps you can debug it yourself with this example.

This will render everything in a pile:
```
<html>
<head><style>span.bigwords { font-size: 32px } span.smallwords { font-size: 12px }</style></head>
<body>
<span class="bigwords">BIG WORDS.</span><br>
<span class="smallwords">ABRACABRAABRACABRA</span>
</body></html>
```

With these changes, everything is not rendered in a pile: https://github.com/RatalaikaGames/litehtml/commit/15319579c5fea3e82230dd31be595168451a4331

However, I feel sure doing this properly is beyond my pay grade. @stasoid I really don't think you'll like how I solve this, but there's my commit so you can judge for yourself.

**Comment by stasoid** [comment]
@mgambrell Alright, I'll do it myself then. Your commit is fine, but I would do it a bit differently.

@tordex To clarify what's going on:
There are three line-heights in question:
<pre>
<a href="https://developer.mozilla.org/en-US/docs/Web/CSS/specified_value">"specified" value</a>,    ->    partially resolved,      ->      fully resolved,
as in CSS:                  or <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/computed_value">"computed" value</a>:             or <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/used_value">"used" value</a>:

"normal" or                 "normal"  ->  "normal"           everything -> px
unitless or                 unitless  ->  unitless
% or                        %         ->  px
px,pt,etc                   px,pt,etc ->  px
</pre>

[The preferred way](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) to specify line-height is unitless number.

Computed value is the one that (should be) inherited.
Before commit de4893f we inherit specified value. After commit de4893f we inherit used value. Both behaviors are not correct, but before commit de4893f unitless number inheritance (the preferred way) was handled correctly.

To fix this situation we should keep both computed and used value of line-height.

This is the minimal example of the issue:
```html
<span style="font-size: 32px"> TEXT<br>TEXT </span>
```
Here `<span>` incorrectly inherits `<body>`'s fully resolved line-height, which was computed based on font size 16px.
