### ISSUE TITLE
mis-selected line height for line breaks when styles are nested

### ISSUE THREAD

**Issue by mgambrell** [litehtml/litehtml#233]
This happens on latest master, but also an older version.. from.. I think... maybe august 30?
Actually the same thing happens on litebrowser.exe from 2015.. kind of, maybe not exactly, but similar problems.

Take this html:
```
<html><body>
<h1>BIG WORDS.<br> <font size=-1>WORDS.<br>MORE WORDS.</font>
<table border=1><tr><td>MORE WORDS.</td></tr></table>
</body></html>
```

We'll be getting the wrong line height used for "words" and "more words". Somehow the bigger line height from the h1 is getting used. And what's more, the entire font size inside the table will be wrong. It should be some default size (I am returning 16 from get_default_font_size()) and yet it's styled exactly as the h1. So in a certain sense, we have two cases where that first h1 styling is getting used (the small text is using its line height, and the table text is using the entire style). 

**UPDATE**: well, I had no closing `<h1>` above. By adding that the h1 styling gets shut down properly. I can live with that, of course. My bad. However the line height is still messed up.

**UPDATE 2**: Setting aside the table, I'm seeing the `<br>` between WORDS and MORE WORDS getting placed in the context of the `<h1>`, thus its css (line height) get used. That `<h1>` has four children (words, break, space, font group). This is strange because in the elements iterator (`litehtml::elements_iterator::process`) the container is the font group and it has three children, as I expect: words, break, and more words. I think this is because of "go inside". Let's check `bool litehtml::go_inside_inline::select`. I see that returning true for my "font" block. That font tag's set to display_inline... sure, that's the default on css_properties. At this point I'm losing track of what's going on. I don't understand why things aren't recursively laid out, this whole idea of "going inside" seems crazy. I added this to `master_css.h` and got the results I wanted: `font { display:inline-block; }` although some things which should be comparable such as `<b>` for instance are set as display:inline. I suppose the difference is that the font size affects placement of things and those others don't... the difference between inline and inline-block is so subtle to me, I don't really know where to go from here. 

I should mention that I'm looking a lot in `render_item_inline_context::new_box` and seeing how dependent it is on font metrics. But it's just using the wrong metrics (from the H1). I haven't been able to fix it satisfactorily to use the "right" metrics but I'm playing with things I don't understand here. It still seems to me the better solution is to force a recursion on the inline placement. 

Note the problem is not with the `<BR>`, if "more words" is many more words such that it line wraps the line spacing is still wrong. But maybe that's the wrong way of looking at it. The breaks may be inserted via layout and get handled the same way. If that's the case then the problem is that breaks get laid out with their contributing line height from the "controlling" element and not the up-to-the-moment font size. OK, I see that we don't get actual BR elements but rather can_hold returns false which makes new_box() get run to effect the line break. 

You know, I felt like I could solve this by using the line height on `el` instead of `this` to make the new line box. It wasn't working, but now that I look into it further, I've got a m_line_height_resolved of 0 again so maybe my fixes in the other bug post arent good enough.

**UPDATE 3** PROGRESS! There are deeper problems in #232 indeed. I also need to set m_line_height_resolved when setting m_line_height, except that's just a kludge; in principle it needs to be resolved AGAIN... well, that's too hard for me right now. So what I did is add set_line_height_resolved, too, and then when `el_text::compute_styles` runs, it uses this: `css_w().set_line_height_resolved(el_parent->css().get_line_height_resolved());`.

NOW, we can change `new_box` as follows:
```
font_metrics fm = el->src_el()->css().get_font_metrics();
m_line_boxes.emplace_back(std::unique_ptr<line_box>(new line_box(line_ctx.top, line_ctx.left + first_line_margin + text_indent, line_ctx.right, el->src_el()->css().get_line_height_resolved(), fm, el->src_el()->css().get_text_align())));
```
After that, we get... one line that's using too-big line-spacing and then further lines that are spaced correctly (use a few hundred ABRACADBRA instead of `WORDS.<br>MORE WORDS.` I think this is due to confusion between before-or-after when the heights are incorporated into the layout.. somehow... I'm out of my league for real now

I think I need to leave it to the experts at this point. Allow me to summarize:
1. due to #232, line heights set on the computed css are currently not working reliably. even if #232 is immediately fixed, there may be deeper issues related to how el_text elements are created--take care to get their line heights set properly!
2. laying out inline content is using the "controlling" element's line height when adding line boxes (`render_item_inline_context::new_box`); instead, it should use... some other line height (and if that's inherited from the controlling element, so be it). What, exactly, should it use? Maybe the maximum of everything that ended up in the line box? Maybe the last element put in the line box? Well, definitely it shouldn't use the "controlling" element.

---

**WORKAROUND** - Don't nest styles and everything works pretty sensibly. I think this is an okay rule for using litehtml, it just took me a long time to discover it..

**Comment by tordex** [comment]
Just commited the fix for bug with the ```<br>``` you've described: 636ba5163a4724fd7bf66664db72f092d4c3be2d

**Comment by mgambrell** [comment]
Thanks!!!!

**Comment by tordex** [comment]
Now the font of table is fixed:
![image](https://user-images.githubusercontent.com/2767018/219867387-8cfe39b3-d445-461a-a5a4-b9f91a3df453.png)

**Comment by mgambrell** [comment]
Thank you!!!
