### ISSUE TITLE
float overlays table

### ISSUE THREAD

**Issue by stasoid** [litehtml/litehtml#251]
Page: http://seasonvar.ru/serial-33668-Belyj_lotos-2-season.html
Problem: image overlays description.
Minirepro:
```html
<div style=float:left>float</div>
<div style=display:table>table</div>
```
Is rendered like this:
![image](https://user-images.githubusercontent.com/2577509/218313073-b6d28bed-9431-40d6-8a96-f9d4fec24e63.png)
Should be:
![image](https://user-images.githubusercontent.com/2577509/218313030-2e7e1844-22e5-41ab-8491-d0fe2b6add5f.png)

**Comment by tordex** [comment]
Fixed

**Comment by stasoid** [comment]
Nice
