### ISSUE TITLE
Most basic display flex example not working

### ISSUE THREAD

**Issue by leonvanderstel** [litehtml/litehtml#260]
For my use case is the ability to interpret flex box a must.

After sifting through the source code I have seen that display flex should be supported. But when I run this basic display flex html css code litehtml renders an empty png. I have used the test container to render litehtml output to png.

I have done some experiments with things as inline-block divs and that is working great.

This is the code.
```
<style type="text/css">
    .parent {
        display: flex;
      justify-content: center;
        background-color: green;
    }
    .child {
        background-color: yellow;
        height: 200px;
        width: 100px;
    }
</style>

<div class="parent">
    <div class="child"></div>
</div>
      
```

What is the status of flex layout in litehtml? Should above mentoined render correctly like the link below? Or does it have constraints, work in progress?

Here you can see the result what it should be. https://html-css-js.com/?html=%0A%3Cstyle%20type=%22text/css%22%3E%0A%20%20%20%20.parent%20%7B%0A%20%20%20%20%20%20%20%20display:%20flex;%0A%20%20%20%20%20%20justify-content:%20center;%0A%20%20%20%20%20%20%20%20background-color:%20green;%0A%20%20%20%20%7D%0A%20%20%20%20.child%20%7B%0A%20%20%20%20%20%20%20%20background-color:%20yellow;%0A%20%20%20%20%20%20%20%20height:%20200px;%0A%20%20%20%20%20%20%20%20wi$*$dth:%20100px;%0A%20%20%20%20%7D%0A%3C/style%3E%0A%0A%3Cdiv%20class=%22parent%22%3E%0A%20%20%20%20%3Cdiv%20class=%22child%22%3E%3C/div%3E%0A%3C/div%3E%0A%20%20%20%20%20%20&css=&js=

**Comment by tordex** [comment]
Flex support is in the nearest plans.

**Comment by xland** [comment]
How about this issue's progress?

**Comment by tordex** [comment]
it is in progress

**Comment by tordex** [comment]
Flexbox layout support is merged.
