### ISSUE TITLE
Build failure with external gtest 1.13.0 which requires C++14

### ISSUE THREAD

**Issue by ryandesign** [litehtml/litehtml#270]
With gtest 1.13.0 installed, building litehtml 0.8 (with my fix for #264) with `-DEXTERNAL_GTEST=ON` fails:

```
/opt/local/include/gtest/internal/gtest-port.h:270:2: error: C++ versions less than C++14 are not supported.
#error C++ versions less than C++14 are not supported.
 ^
```

This further fix works for me:

```diff
--- CMakeLists.txt.orig	2023-05-13 16:46:25.000000000 -0500
+++ CMakeLists.txt	2023-06-19 01:42:57.000000000 -0500
@@ -204,7 +204,7 @@
     )
 
     set_target_properties(${TEST_NAME} PROPERTIES
-        CXX_STANDARD 11
+        CXX_STANDARD 14
         C_STANDARD 99
         PUBLIC_HEADER "${HEADER_LITEHTML}"
     )
```

**Comment by asmaloney** [comment]
I think this can be closed since litehtml [now requires C++17](https://github.com/litehtml/litehtml/blob/554fcc70b4e3a00021eaf1376b6d651a3c70a499/CMakeLists.txt#L189)?

**Comment by tordex** [comment]
> I think this can be closed since litehtml [now requires C++17](https://github.com/litehtml/litehtml/blob/554fcc70b4e3a00021eaf1376b6d651a3c70a499/CMakeLists.txt#L189)?

Yes, thank you.
