### ISSUE TITLE
some compilers don't like casting void* to enum directly...

### ISSUE THREAD

**Issue by mgambrell** [litehtml/litehtml#273]
Well, that's annoying:
https://github.com/litehtml/litehtml/blob/2d5e9b614a70c3060dc0408180118c982ac95a25/src/gumbo/error.c#L82

> warning : cast to smaller integer type 'GumboTag' from 'void *' [-Wvoid-pointer-to-enum-cast]

I don't think this is a very helpful diagnostic.... but we should probably fix it.

I suggest doing this: 

`GumboTag tag = (GumboTag)(uintptr_t)error->tag_stack.data[i];`

(I checked and gumbo is already using stdint.h elsewhere)

**Comment by tordex** [comment]
Fixed. Thank you for reporting.
