### ISSUE TITLE
Endless cycle in litehtml::css::parse_stylesheet(...)

### ISSUE THREAD

**Issue by mgayanov** [litehtml/litehtml#276]
Hello!

```cpp
void litehtml::css::parse_stylesheet(const char* str, const char* baseurl, const std::shared_ptr<document>& doc, const media_query_list::ptr& media)
{
	string text = str;

	// remove comments
	string::size_type c_start = text.find("/*");
	while(c_start != string::npos)
	{
		string::size_type c_end = text.find("*/", c_start + 2);
		text.erase(c_start, c_end - c_start + 2);
		c_start = text.find("/*");
	}
```

This code assumes that for every `/*` there will be corresponding `*/`

But if `*/` doesn't exist, `c_end` will become -1, `text` will not change because

`c_end - c_start + 2` < 0 if `c_start > 0` 

 and `c_start` will not change too, so cycle will never end

**Comment by tordex** [comment]
Thank you for bug report. This issue is fixed in the last commit.
