### ISSUE TITLE
vw and vh are not supported

### ISSUE THREAD

**Issue by bigfatbrowncat** [litehtml/litehtml#3]
First of all, thank you very much for your awesome engine. I've decided to use it in my http://github.com/bigfatbrowncat/zetes project. And I'll donate some money to you as soon as I earn some with it :)

But there is a small feature that I miss much. It's the viewport units <code>vw</code> and <code>vh</code>. http://www.w3schools.com/cssref/css_units.asp, http://caniuse.com/#feat=viewport-units. It's very useful especially when you try to make a solid web-application-like UI with relative positioning of some views.

As I found out in your code, implementing it is not too hard, but I'm afraid of doing it by myself - no one knows the code better than the author.

Would you be so kind to do that?

**Comment by tordex** [comment]
Please check the [vw-vh](https://github.com/litehtml/litehtml/tree/vw-vh) branch. I've added *vh*, *vw*, *vmin* and *vmax* support there.
Currently the viewport units implementation have one issue: the changes in the media features are ignored. The media properties are retrieved on document creation (see document::createFromUTF8) and will be ignored in if you call the document::media_changed.

**Comment by bigfatbrowncat** [comment]
Thank you! That looks pretty clear. I'll use it in my wrapper when you merge it upstream.

By the way, is absolute and relative positioning implemented yet? I'm not sure...

**Comment by tordex** [comment]
I've merged changes into master branch.
