### ISSUE TITLE
4-byte utf-8 sequences (emoji) are broken inside litehtml

### ISSUE THREAD

**Issue by georgehazan** [litehtml/litehtml#314]
They are suddenly converted into 3-byte sequences (F0 9F A4 A3 -> ef a4 a3) and then drawn as chinese characters
Test html file is attached
[qq.zip](https://github.com/litehtml/litehtml/files/14812558/qq.zip)

**Comment by stasoid** [comment]
You are on Windows and you are using litehtml_to_wchar/utf8_to_wchar in your container, right? Those functions incorrectly work with Unicode characters above 0xFFFF on Windows.

**Comment by tordex** [comment]
Just checked this issue on Windows. Actually litehtml converts from/to UTF-32. On Linux ```sizeof(wchar_t) == 4```, on Windows ```sizeof(wchar_t) == 2```. That's why there are issues with unicode characters above 0xFFFF on Windows.

Replaced wchar_t with char32_t and renamed ```utf8_to_wchar``` to ```utf8_to_utf32``` and ```whar_to_utf8``` to ```utf32_to_utf8```

**Comment by stasoid** [comment]
Nice. Finally all vestiges of wchar_t are eradicated.

**Comment by georgehazan** [comment]
@stasoid @tordex thanks for the fix, but there're also 5-6 bytes long utf-8 sequences, so anyway you'd have to deal with UTF32-LE instead of UTF16-LE in the previous case
