### ISSUE TITLE
clarification of offset in gradient.color_points

### ISSUE THREAD

**Issue by kobalicek** [litehtml/litehtml#318]
Both linear and radial gradient seem to use offset in color_points normalized to [0, 1], which is what 2D APIs typically consume. However, conic gradient provides angles specified as degrees in the `offset` field, so a stop's `offset` could be `360`, for example.

I'm not sure whether this is just a bug or intention.

**Comment by tordex** [comment]
This is not a bug. Radial and linear gradients operate with something like _vector_ and coordinates depend of start/end points. Conic gradient operates with angles only. So I decide to pass angle as offset.

**Comment by kobalicek** [comment]
Ok, thanks for the clarification.

BTW This is how it looks rendered by Blend2D. I think it's pretty nice:

![image](https://github.com/litehtml/litehtml/assets/6491301/4478856c-39e0-47b2-ae75-2afc030e7eee)
