### ISSUE TITLE
litehtml::render_item_block - unused variable warning

### ISSUE THREAD

**Issue by kobalicek** [litehtml/litehtml#319]
There is a following code in `litehtml::render_item_block::init()`:

```
    {
        css_selector sel;
        sel.parse(".inline_rating");
        if(src_el()->select(sel))
        {
            int i = 0;
            i++;
        }
    }
```

This part makes no sense:

```
{
  int i = 0;
  i++
}
```

Is that a bug or what is the intention of that code?

(BTW compiler warns about that - variable set, but never used)

**Comment by tordex** [comment]
This is debug code. I've removed it in [b4d74c3](https://github.com/litehtml/litehtml/commit/b4d74c388990f383c234a0a9bc55580e3e5727e5). Thank you for pointing this out.

**Comment by kobalicek** [comment]
Great thanks!
