### ISSUE TITLE
litehtml::flex_line::distribute_free_space - sum_flex_factors never used:

### ISSUE THREAD

**Issue by kobalicek** [litehtml/litehtml#320]
The `sum_flex_factors` variable in `litehtml::flex_line::distribute_free_space()` is accumulated, but it's never read.

(BTW compiler generates a warning about this: variable set but never used)

**Comment by tordex** [comment]
What compiler version do you use? My gcc 13.2.1 doesn't show warning here :(

Anyway, removed this variable here [0c1b0c7](https://github.com/litehtml/litehtml/commit/0c1b0c7bafe4efab53414c541513dd7e7ec2e579)

**Comment by kobalicek** [comment]
I'm usually using clang for development, sometimes even my own compiled clang from git :)

This warning was emitted by the latest `clang 18.1` with `-Wall -Wextra` flags, which is the usual combination that I'm using.

Thanks for fixing it!
