### ISSUE TITLE
document_container::draw_solid_fill() and background_layer's is_root

### ISSUE THREAD

**Issue by asmaloney** [litehtml/litehtml#326]
In `document_container::draw_solid_fill()`, I am trying to use the background_layer's _is_root_ to clear my widget's background, but draw_solid_fill() is never called with is_root set to true.

The comment for `is_root` says:
>  is_root is true for root element. Container can use this flag to apply background to the top window.

Do I need to do something special to get this set properly? Or am I supposed to clear the background somewhere other than `draw_solid_fill`?

**Comment by tordex** [comment]
litehtml calls background functions with ```is_root``` only if one of the properties ```background-color``` or ```background-image``` are defined for ```<html>``` tag.

litehtml doesn't know what is the _default_ color. So you have to fill your window with default color first and then litehtml redraw background over default, if it is defined in CSS.

**Comment by asmaloney** [comment]
Thanks Yuri.

> So you have to fill your window with default color first

I don't know what the colour is until I get it from the CSS though.

I have `background-color` set on `<body>`.

With Firefox it fills the entire background and I get this:

<img width="154" alt="Screen Shot 2024-04-22 at 18 54 23 PM" src="https://github.com/litehtml/litehtml/assets/391371/112c628c-812e-4242-99f8-9e1aa17f137e">

With my own litehtml-derived widget I get white margins (widget background colour) on the left & right like this:

<img width="126" alt="Screen Shot 2024-04-22 at 18 54 39 PM" src="https://github.com/litehtml/litehtml/assets/391371/edfec107-0fdd-4a59-b6bb-32b821337934">

(That's whitespace to the widget's left edge.)

Maybe I'm missing something in my implementation? Is this related to `get_client_rect`? I haven't figured that part out yet.

**Comment by tordex** [comment]
The litebrowser has the same behavior. I'll look into this.

**Comment by tordex** [comment]
Anyway, setting background color for ```<html>``` tag must work. I works with litebrowser.

**Comment by asmaloney** [comment]
Ah - just [found this](https://www.w3.org/TR/css-backgrounds-3/#body-background) which might be of interest:

> For documents whose root element is an HTML html element or an XHTML html element [HTML]: if the computed value of background-image on the root element is none and its background-color is transparent, user agents must instead propagate the computed values of the background properties from that element’s first HTML body or XHTML body child element.

So it looks like the `body` background colour should be used as "root" in my case.

**Comment by tordex** [comment]
> So it looks like the `body` background colour should be used as "root" in my case.

Yes it should do this, but stopped because of bug in code. I've fixed it in commit [554fcc7](https://github.com/litehtml/litehtml/commit/554fcc70b4e3a00021eaf1376b6d651a3c70a499).

**Comment by asmaloney** [comment]
Fixed! Thanks a lot Yuri.

(And thanks for this library. I'm having fun implementing my widget & see it coming together piece-by-piece. If I could only figure out `litehtml -> PDF` I could get rid of my embedded chromium!)
