### ISSUE TITLE
Suggestion: Add a clang-format file for code formatting

### ISSUE THREAD

**Issue by asmaloney** [litehtml/litehtml#328]
Would the maintainers consider adding a clang-format file so contributors (and you) don't need to waste time on code formatting?

The easiest path would be to pick one of the "standard" [code styles](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#basedonstyle), but it can be customized/tuned if they are unacceptable.

Code formatting with clang-format can be enforced using CI.

**Comment by tordex** [comment]
Yes, you are right. Will do this some later.
