### ISSUE TITLE
Compilation on Linux (Ubuntu Vivid) fails

### ISSUE THREAD

**Issue by dmgolubovsky** [litehtml/litehtml#33]
Hi

I cannot compile litebrowser-linux (and litehtml) on Ubuntu Vivid

most of errors say things like 'shared_ptr' is not a memb
er of 'std'

$ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/golubovsky/src/litebrowser-linux

$ make

In file included from /home/golubovsky/src/litebrowser-linux/litehtml/src/html.h:12:0,
                 from /home/golubovsky/src/litebrowser-linux/litehtml/src/background.cpp:1:
/home/golubovsky/src/litebrowser-linux/litehtml/src/types.h:14:23: error: 'shared_ptr' is not a member of 'std'
  typedef std::vector< std::shared_ptr<litehtml::element> >  elements_vector;
                       ^
/home/golubovsky/src/litebrowser-linux/litehtml/src/types.h:14:23: error: 'shared_ptr' is not a member of 'std'
/home/golubovsky/src/litebrowser-linux/litehtml/src/types.h:14:56: error: template argument 1 is invalid
  typedef std::vector< std::shared_ptr<litehtml::element> >  elements_vector;
                                                        ^
...

$ g++ --version
g++ (Ubuntu 4.9.2-10ubuntu13) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I do not program in C++ so cannot give further diagnostics, and sorry for stupid questions. My plans are to integrate litehtml with another language (possibly Haskell) via standard FFI tools, but I need to compile it first.

For e. g. shared_ptr I have files defining it installed:

/usr/include/c++/4.9/bits/shared_ptr.h
/usr/include/c++/4.9/tr1/shared_ptr.h
/usr/include/boost/asio/detail/shared_ptr.hpp
/usr/include/boost/serialization/shared_ptr.hpp
/usr/include/boost/smart_ptr/shared_ptr.hpp
/usr/include/boost/interprocess/smart_ptr/shared_ptr.hpp
/usr/include/boost/shared_ptr.hpp

My understanding is that I do not pass proper options to g++. What extra options need to be given to compile on Linux?

Thanks.

**Comment by dmgolubovsky** [comment]
Compile log on gist:

https://gist.github.com/dmgolubovsky/4aae92959be45c362438

**Comment by tordex** [comment]
You need the option ```-std=c++11``` to compile *.cpp files and ```-std=c99``` to compile *.c files (gumbo-parser). The compiler options can be found inside the CMakeLists.txt.

**Comment by dmgolubovsky** [comment]
Thanks.

 cmake -DCMAKE_BUILD_TYPE=RELEASE . did it.

Now I am getting compilation errors in table.cpp

cat ../../make.log 
/home/golubovsky/src/litebrowser-linux/litehtml/src/table.cpp: In member function 'void litehtml::table_grid::calc_rows_height(int, int)':
/home/golubovsky/src/litebrowser-linux/litehtml/src/table.cpp:528:35: error: invalid initialization of non-const reference of type 'std::reverse_iterator<__gnu_cxx::__normal_iterator<litehtml::table_row*, std::vector<litehtml::table_row> > >&' from an rvalue of type 'std::vector<litehtml::table_row>::reverse_iterator {aka std::reverse_iterator<__gnu_cxx::__normal_iterator<litehtml::table_row*, std::vector<litehtml::table_row> > >}'
    for (auto& row = m_rows.rbegin(); row < m_rows.rend() && extra_height > 0; row++)
                                   ^
make[2]: *** [litehtml/CMakeFiles/litehtml.dir/src/table.cpp.o] Error 1
make[1]: *** [litehtml/CMakeFiles/litehtml.dir/all] Error 2
make: *** [all] Error 2

Thanks.

**Comment by tordex** [comment]
I've updated sources to avoid this bug (commit dfc2b9c), please try to compile it now.

**Comment by dmgolubovsky** [comment]
Thanks. I am able to compile the browser.
