### ISSUE TITLE
Other modernization cleanups?

### ISSUE THREAD

**Issue by asmaloney** [litehtml/litehtml#336]
If I get the urge to do some more busy-work while procrastinating 😄 , would you accept PRs for any of the following style modernizations via clang-tidy?

- [return brace list](https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/modernize/return-braced-init-list.html)
- [= default](https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/modernize/use-equals-default.html)
-  [range-based loops](https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/modernize/loop-convert.html)
- [.empty()](https://releases.llvm.org/17.0.1/tools/clang/tools/extra/docs/clang-tidy/checks/readability/container-size-empty.html)

**Comment by tordex** [comment]
This would be great! Yes, I'll accept this PR.

**Comment by asmaloney** [comment]
Done for now! 😄

**Comment by tordex** [comment]
Thank you very much!
