### ISSUE TITLE
Table border="0" sending me border widths of 1 

### ISSUE THREAD

**Issue by asmaloney** [litehtml/litehtml#338]
I have a table like this:

```html
<html><body><table border="0" cellpadding="0">
<tr>
<th width="30"/><th width="50"/><th width="150"/>
</tr>
<tr>
<td>&nbsp;</td>
<td>Thing 1</td>
<td>Thing 2</td>
</tr>
<tr>
<td>&nbsp;</td>
<td>Thing 3</td>
<td>Thing 4</td>
</tr>
</table></body></html>
```

When I receive the data in my `document_container::draw_borders()` implementation, all the border widths are 1, so it draws like this:
<img width="137" alt="Screen Shot 2024-04-22 at 17 13 38 PM" src="https://github.com/litehtml/litehtml/assets/391371/9538ea95-4542-4a09-bd9a-e8a267e6e70e">

The same table renders correctly (no borders) with chromium.

I tried tracing through - the `border` attribute is read correctly as `0`, but somewhere along the way the table borders get set to 1. I kinda got lost while stepping through since I don't understand the architecture - what happens between reading the attribute and me receiving it? Any idea where I might look?

**Comment by tordex** [comment]
Hmm... replacing ```border="0"``` attribute with ```style="border-width: 0"``` solves the issue. I'll look into this.
