### ISSUE TITLE
Possible copy-paste bug in element.h

### ISSUE THREAD

**Issue by dartraiden** [litehtml/litehtml#366]
https://github.com/litehtml/litehtml/blob/20b3fc6c004267855ce7db794815171309d8a6ea/include/litehtml/element.h#L211

```
	inline bool element::is_block_box() const
	{
		if (css().get_display() == display_block ||
			css().get_display() == display_flex ||
			css().get_display() == display_table ||
			css().get_display() == display_list_item ||
			css().get_display() == display_flex)
		{
			return true;
		}
		return false;
	}
```

`css().get_display() == display_flex` is checked twice.

**Comment by tordex** [comment]
Yes, you are right. This is copy-paste bug. Fixed in the last commit. Thank you!
