### ISSUE TITLE
Is it support custom font ?

### ISSUE THREAD

**Issue by octalflow** [litehtml/litehtml#370]
thank you.

**Comment by tordex** [comment]
What is "custom font"? ```litehtml``` supports ```<font>``` tag and font related CSS properties. All you need is implement text/font related functions of  ```document_container``` like ```document_container::create_font```.

**Comment by octalflow** [comment]
Does it support src : url(myFont) ?

**Comment by tordex** [comment]
Do you mean [@font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) at rule?

**Comment by octalflow** [comment]
yes.

**Comment by tordex** [comment]
No, not supported. Added to the ToDo list.

**Comment by octalflow** [comment]
thank you.
