### ISSUE TITLE
Can't get it working consistently.

### ISSUE THREAD

**Issue by blitz-research** [litehtml/litehtml#39]
I've got this working OK on Mac, but for some reason I can't get it working consistently on Windows/Linux.

The page I'm trying to load is here:

http://www.monkey-x.com/docs/html/Home.html

Each time I load it, something is slightly wong, like a border is added to the top table, or margins are 0, or font size is wrong. This seems like it must be an uninitialized var issue, but I can't find anything - even checked with valgrind.

The page works OK(ish) in litebrowser - but then, that didn't appear to leak memory either. Is litebrowser built with *exactly* the same version of litehtml as the one in github? The windows container code in the github source seems slightly wrong - eg: it uses cssborder instead of border in places etc. Is that out of date?

**Comment by blitz-research** [comment]
Ok, I've narrowed it down to css containing duplicate elements, eg:

```
h1{
  line-height: 10px;
}
h1{
  line-height: 100px;
}
```

I'm not actually sure what's supposed to happen here, but both chrome and windows litebrowser use the second one.

However, in my project it seems to pick one at random!

Are you perhaps using a pointer as a map key somewhere?

**Comment by blitz-research** [comment]
Okay, found a quick fix!

The code is sorting selectors 'by pointer', which will effectively give selectors for the same elements a random order since pointer values are pretty much random.

Removing the sort from css::sort_selectors does the trick, ie:

void litehtml::css::sort_selectors()
{
	//sort(m_selectors.begin(), m_selectors.end(), std::less<css_selector::ptr>( ));
}

This doesn't seem to have any impact here, but I assume it's there for a reason...

**Comment by Kwizatz** [comment]
Hi, it seems you have been looking into the code more than I have, so I am not sure of how much help my input is. I did noticed the previous issue with missing virtual destructors, some other classes might also need them by the way.

Anyway, as I said, I haven't looked deeply into the the code here, so I might be way off.
if m_selectors is a container of pointers then sorting 'as-is' is as pointless (no pun intended) as you have pointed out (again, no pun intended). Sorting may help for doing a binary search, but then you need to know what you're looking for in your search, what should m_selectors should be ordered by?.
I am guessing that you probably want to sort by property name, IE: "line-height" and do binary searches by it as well. So you need to implement a bool operator < (const css_selector::ptr,const css_selector::ptr) that dereferences the pointers and compares with < whatever data the container needs to be sorted by.

Maybe that helps or gives you an idea on what to look for. I may look into it later on, my project is not as advanced as yours seems to be.

Best Regards.

**Comment by tordex** [comment]
Selectors sorted by specificity and order (index index in file). Disabling the sorting will break some things (like ```!important``` attribute).

The file css_selector.h already contains the implementation of < operator with pointers:
```C++
	inline bool operator < (css_selector::ptr v1, css_selector::ptr v2)
	{
		return (*v1 < *v2);
	}
```

**Comment by Kwizatz** [comment]
then change 
sort(m_selectors.begin(), m_selectors.end(), std::less<css_selector::ptr>( ));
to
sort(m_selectors.begin(), m_selectors.end());

so the operator is used instead of std::less

**Comment by Kwizatz** [comment]
Looking at the code for std::sort in Visual Studio, it doesn't make much of a difference if you removed the less parameter, but I am not sure. Unit Tests would help here to see what exactly is going on, whether the operator is being called or not.

**Comment by tordex** [comment]
I've tried in Visual Studio 2013 - the operator < is called correctly. I'll test on Linux.

**Comment by Kwizatz** [comment]
Yuri, is that container supposed to contain duplicates? perhaps the problem is in allowing duplicate entries for the same property.

**Comment by tordex** [comment]
No, there are no duplicates. Even everything is same, litehtml writes index into the selector and compare by this index also.

Finally, I've reproduced the bug on Linux. I don't know why, but the ```operator <``` is not called there. Anyway this code is working correctly:
```C++
void litehtml::css::sort_selectors()
{
	std::sort(m_selectors.begin(), m_selectors.end(),
		 [](const css_selector::ptr& v1, const css_selector::ptr& v2)
		 {
			 return (*v1) < (*v2);
		 }
	);
}
```
@blitz-research, please can you test it?

**Comment by blitz-research** [comment]
I can confirm that either std::sort without the std::less param, or the lambda comparison work here.

I should probably mention I'm using mingw on Windows, although the problem does also happen on Linux. Oddly, it's never happened on Mac so I suspect a c++ library bug.

**Comment by Kwizatz** [comment]
Or gcc related. There is template magic mixed with the inline magic of the operator in there, gcc has bitten me in the rear before with inline functions. may be the case that when less is instanced it has not seen the declaration of the operator for some reason and thus it uses plain pointer comparison.

I like removing less as a solution because it is less code to worry about, but it is your call.

It may be worth something trying the original code with a non inline operator < just to narrow the cause of the issue.

**Comment by blitz-research** [comment]
I think it may be something to do with std::less being specialized for shared_ptr, although it still looks like it's doing the wrong thing to me.

I think I prefer the lambda solution as it's more explicit, with less chance of something else 'weird' happening.

I'm definitely gonna look at this on Mac though and see if the correct operator< is being used there.

**Comment by tordex** [comment]
Well, I've commited changes with lambda into the master branch
