### ISSUE TITLE
need help with draw_background implementation

### ISSUE THREAD

**Issue by RalfSchallenberg** [litehtml/litehtml#4]
Dear Yuri,

could you add some more documentation to the Wiki explaining how to implement the various functions in a `document_container`? I'm in the process of implementing my own `document_container`-derived class and I'm kind of stuck in the `draw_background` function right now.
Could you explain the meaning of the elements in the **`background_paint`** class?
Thank you!

**Comment by tordex** [comment]
I've added [background_paint](https://github.com/litehtml/litehtml/wiki/background_paint) into wiki.

**Comment by RalfSchallenberg** [comment]
Thanks, that was quick! I think this will help a lot. :)
