### ISSUE TITLE
BaseUrl question

### ISSUE THREAD

**Issue by NuclearCookie** [litehtml/litehtml#40]
Hi @tordex,

It seems like there are 2 ways the `<base>` tag is implemented. There is the `set_base_url` method of the container ( so the client has to cache the url ), and there is the `baseurl` argument in methods like `load_image`, `get_image_size` and so on. Isn't it the same thing? 
Is it ok to remove the second implementation? ( It's pretty complex with the custom styles like `background-image-baseurl` 

Thanks

**Comment by tordex** [comment]
I have to explain how the ```<base>``` is used. the document_container::set_base_url is called from ```el_base::parse_attributes``` and it is the ```href``` attribute value as-is. You need save this value and use every time when ```load_image``` or ```get_image_size``` have null value in parameter ```baseurl```.

Here we have a problem with images in CSS files. As you know, if the uri in CSS is relative, the base path is the CSS file location. Now look at ```document_container::import_css```:
```C++
virtual void import_css(litehtml::tstring& text, const litehtml::tstring& url, litehtml::tstring& baseurl) = 0;
```
This function process the CSS file loading from with ```<link>``` tag. Here ```href``` is raw href tag parameter. So you can load valid CSS file using the saved base url (if needed). And return the base url in ```baseurl``` for images in loaded CSS file. Actually the returned value in ```baseurl``` can be just a label to identify the image location. litehtml does not process the base url, it just pass it back to your code as parameter of ```load_image``` and ```get_image_size```.

As for ```background-image-baseurl```, you don't need to use this css property. litehtml set it automatically into ```baseurl``` from ```import_css``` function to identify image source.

I hope this is clear.

**Comment by NuclearCookie** [comment]
Thank you for the switf explanation.
I was not aware that the `<base>` does not apply to css files. That explains my confusion :)
