### ISSUE TITLE
strings.h not available in msvc 2015

### ISSUE THREAD

**Issue by feliwir** [litehtml/litehtml#43]
I can't compile litehtml since there is no strings.h on msvc. 
This can be solved by using:
```
#ifndef _WIN32
#include <strings.h>
#endif
```

Should be added to every sourcefile including strings.h

**Comment by tordex** [comment]
As I understand the strings.h is part of gumbo parser. And this file can be found inside the "src/gumbo" subfolder. I guess you have to add the "gumbo" folder into include paths. Anyway using ```#ifndef _WIN32``` is not correct, this file is for Windows platform.

**Comment by NuclearCookie** [comment]
Make sure you cloned the submodules ( git clone --recursive )

**Comment by feliwir** [comment]
seems like i didn't clone the submodules :( Shame on me

**Comment by NuclearCookie** [comment]
If you change the include to `#include "strings.h"` it should work too without the ifndef :)

**Comment by feliwir** [comment]
Yeah, i noticed that aswell by now :) It's still a bug though

**Comment by NuclearCookie** [comment]
I'll see if I can come up with a solution today. I'll let you know what I find

**Comment by NuclearCookie** [comment]
what tordex is saying is correct. the strings.h file in the gumbo folder should be sufficient on windows. because the include uses angular brackets, on other platforms it will take the system strings.h. So as said before, double check that the gumbo folder has been added as an include directory in your solution

**Comment by feliwir** [comment]
As i use the CMake files it is not added to the solution. So you should think about adding this as an include directory in your CMakeLists.txt

**Comment by feliwir** [comment]
There should be no need to edit any project files generated by cmake manually (since that would pretty much destroy the use of cmake)

**Comment by NuclearCookie** [comment]
Do you think you can add it yourself and create a Pull Request?

**Comment by feliwir** [comment]
Sure

**Comment by tordex** [comment]
Thank you for pull request. I've merged it.
