### ISSUE TITLE
"fit to the document" doesn't work in practice

### ISSUE THREAD

**Issue by wjrogers** [litehtml/litehtml#50]
I have been working on using litehtml to render tooltips. I have made good progress, but I'm stumped on how to fit the tooltip size to the document. The wiki says,
> If you don't have the fixed size window to draw HTML, you need to get the HTML best width. It is very easy: document::render returns the best width for you.

I call render like this:
```
    _width = document->render(900);
    if (_width < max_width)
        _width = document->render(_width);
```

The problem is that `render` always returns the width I set in `document_container::get_client_rect` no matter how small the HTML is. I tried not setting a width in `get_client_rect`, but then litehtml tries to render in the minimum width possible, wrapping text at every word.

Is there a practical way to make use of the "optimal width" feature?

**Comment by NuclearCookie** [comment]
If you render your html page in another browser, and you inspect it, does the body fit the content of your tooltip or does it extend to the full screen? If it extends to the full screen, what you just described seems the expected behaviour.

**Comment by tordex** [comment]
This is possible to fit into document like you want. The problem in the default styles of ```body``` and ```html``` tags. In the master.css these tags are defined as:
```
html {
    display: block;
    height:100%;
    width:100%;
	position: relative;
}

body {
	display:block; 
	margin:8px; 
    height:100%;
    width:100%;
}
```
The height and width are 100% for both tags. This is makes rendered document as wide as possible. 

To fix the problem for tooltips just use your own master css and define height and width as ```auto```. 

Also you can pass the updated styles in the ```user_styles``` parameter of ```litehtml::document::createFromString``` function.

The user style is:
```
body
{
    width:auto;
    height:auto;
}

html
{
    width:auto;
    height:auto;
}
```
The code to parse the css:
```C++
litehtml::css styles;
LPWSTR css_tips = L"<string with css text>"
styles.parse_stylesheet(
	css_tips, 
	<base url can be NULL>, 
	litehtml::document::ptr(), // no document
	litehtml::media_query_list::ptr() //empty media queries
	);
```

**Comment by wjrogers** [comment]
Ah, I didn't think to investigate the master css. I'm able to get the sizing I expected now. Thank you!
