### ISSUE TITLE
Problem: incorrect image size

### ISSUE THREAD

**Issue by Umkerius** [litehtml/litehtml#53]
I've tried to load page http://wbp.wotb.com.wots.iv/en/news/blitz-client/11111/nastya19/?width=612 and have a problem with image size:
![fadinmedal](https://cloud.githubusercontent.com/assets/7581547/14883203/87867b00-0d45-11e6-8076-2cea528a5148.jpg)
The same image has normal size in Chrome:
![fadinmedalnormal](https://cloud.githubusercontent.com/assets/7581547/14883261/fedfdd9a-0d45-11e6-850f-62257250ce5a.jpg)
Tag "Div" which contains image, has max-width property 40%; image has 100%.
During page rendering, html_tag::render_box method calculates width of div element (150px * 0.4 == 66px) and use it for rendering of their children (img element). 
I don't know how to fix this problem correctly. Any suggestions?

**Comment by Umkerius** [comment]
If I comment code
// check for max-width
if (!m_css_max_width.is_predefined()) {...}
Image has a normal size :)))

**Comment by tordex** [comment]
Something wrong with URL. I can't to open it.

**Comment by Umkerius** [comment]
Try this one: http://wotblitz.ru/ru/news/pc-browser/specials/supremacy_2/
You can see the same problem

**Comment by tordex** [comment]
I see the images are smaller. But the aspect ration is correct in the litebrowser. I'll look into this. Thank you.
