### ISSUE TITLE
Flexbox support?

### ISSUE THREAD

**Issue by bnolan** [litehtml/litehtml#56]
Flexbox support (as seen in react-native) would be amazing. Any chance of that? Or hints as to how it could be implemented?

**Comment by bnolan** [comment]
ps: Litehtml is wonderful, thank you very much, I just got it going with a SDL2 container (repo coming soon) and it's been very fun. 😸

**Comment by bnolan** [comment]
Here's the gist, it's very unfinished, but the basics work.

https://gist.github.com/bnolan/436dd93893a6067406ce1a0b9e2dc0f3

**Comment by bnolan** [comment]
Also, `* {box-sizing: border-box}` would be awesome.

**Comment by LiamKimChan** [comment]
yep, flexbox support would be great

**Comment by tordex** [comment]
Flex layout support will be released in issue #260
