### ISSUE TITLE
Add better support for ordered lists

### ISSUE THREAD

**Issue by nafest** [litehtml/litehtml#59]
Currently litehtml does not render the ordinal of a list item in an ordered list. It would be nice to have at least support for list_style_type_decimal. I'd like to use litehtml with a markdown to html converter and ordered lists seem to be the only thing that is missing.

I'd suggest to extend the list_marker struct with a font and a value member, such that document_container::draw_list_marker can cope with list_style_type_decimal.

I extended litehtml::html_tag::draw_list_marker in a prototypical manner (see https://github.com/nafest/litehtml/commit/d42d93860051840d0b366b4ecbc04f4ffb4ff4d4) to set these two members, but I am not quite sure if this is the right place for this logic.

**Comment by tig** [comment]
Sigh. I just discovered litehtml does not appear to support ordered lists. Consider this a vote for getting that implemented.

**Comment by tordex** [comment]
@lexxmark Thank you for your work. I've merged your changes. But I've changed the way the ordered lists markers are drawn. Look at commit 58e92d6dc649c4be469fad4912cc4ce25c6f11a5. 

Supported list-style-type: decimal, decimal-leading-zero, lower/upper-latin, lower/upper-alpha, lower/upper-roman, lower-greek. Also you don't need draw marker in `document_container::draw_list_marker`.

**Comment by lexxmark** [comment]
@tordex That's even better, thank you for moving stuff from container class and implementing other list types.

I just forgot to mention that I used 1-based index in the "list_index" attribute. I think the right way is to use 0-based index there.

Just replace
```
tchar_t val[2] = { 1, 0 };
```  
to
```
tchar_t val[2] = { 0, 0 };
```
