### ISSUE TITLE
how to use litehtml and html file to do the ui of desktop program

### ISSUE THREAD

**Issue by cathaychen** [litehtml/litehtml#60]
i want to develop desktop program， use html element to deal the ui and layout by litehtml lib，but i don't know how to do interaction between html element and desktop program， could you help me？

**Comment by tordex** [comment]
Currently you can use litehtml to create the simple interface only. Interaction with anchors are made via document_container::on_anchor_click. So you can get an notification when user click any anchor.

To support forms you have to create custom elements. I've tried this yet, so maybe some changes in litehtml are required.

**Comment by barthoukes** [comment]
Didi you consider DJANGO. It is a combination of HTML where Python can fill in stuff.
