### ISSUE TITLE
Compile and get it to run?

### ISSUE THREAD

**Issue by EkanshdeepGupta** [litehtml/litehtml#62]
Hi! I was interested in Litehtml and decided to try it out for myself.

I downloaded the .zip, ran cmake, then make. There were no errors. I ended up with a folder CMakeFiles which had all compiled files under /litehtml.dir/src, and a new file liblitehtml.a which my archive manager refuses to open. How do I run this software? I see no executable. What am I missing? Thanks, and sorry if this is a trivial question.

`$ cmake .
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- No build type selected, default to Release
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ekansh/Downloads/litehtml-320810f2f4faa78626fc6df8130bae9de42ba988

$ make
Scanning dependencies of target litehtml
[  2%] Building CXX object CMakeFiles/litehtml.dir/src/background.cpp.o
[  4%] Building CXX object CMakeFiles/litehtml.dir/src/box.cpp.o
[  6%] Building CXX object CMakeFiles/litehtml.dir/src/context.cpp.o
[  8%] Building CXX object CMakeFiles/litehtml.dir/src/css_length.cpp.o
[ 10%] Building CXX object CMakeFiles/litehtml.dir/src/css_selector.cpp.o
[ 12%] Building CXX object CMakeFiles/litehtml.dir/src/document.cpp.o
[ 14%] Building CXX object CMakeFiles/litehtml.dir/src/el_anchor.cpp.o
[ 17%] Building CXX object CMakeFiles/litehtml.dir/src/el_base.cpp.o
[ 19%] Building CXX object CMakeFiles/litehtml.dir/src/el_before_after.cpp.o
[ 21%] Building CXX object CMakeFiles/litehtml.dir/src/el_body.cpp.o
[ 23%] Building CXX object CMakeFiles/litehtml.dir/src/el_break.cpp.o
[ 25%] Building CXX object CMakeFiles/litehtml.dir/src/el_cdata.cpp.o
[ 27%] Building CXX object CMakeFiles/litehtml.dir/src/el_comment.cpp.o
[ 29%] Building CXX object CMakeFiles/litehtml.dir/src/el_div.cpp.o
[ 31%] Building CXX object CMakeFiles/litehtml.dir/src/element.cpp.o
[ 34%] Building CXX object CMakeFiles/litehtml.dir/src/el_font.cpp.o
[ 36%] Building CXX object CMakeFiles/litehtml.dir/src/el_image.cpp.o
[ 38%] Building CXX object CMakeFiles/litehtml.dir/src/el_link.cpp.o
[ 40%] Building CXX object CMakeFiles/litehtml.dir/src/el_para.cpp.o
[ 42%] Building CXX object CMakeFiles/litehtml.dir/src/el_script.cpp.o
[ 44%] Building CXX object CMakeFiles/litehtml.dir/src/el_space.cpp.o
[ 46%] Building CXX object CMakeFiles/litehtml.dir/src/el_style.cpp.o
[ 48%] Building CXX object CMakeFiles/litehtml.dir/src/el_table.cpp.o
[ 51%] Building CXX object CMakeFiles/litehtml.dir/src/el_td.cpp.o
[ 53%] Building CXX object CMakeFiles/litehtml.dir/src/el_text.cpp.o
[ 55%] Building CXX object CMakeFiles/litehtml.dir/src/el_title.cpp.o
[ 57%] Building CXX object CMakeFiles/litehtml.dir/src/el_tr.cpp.o
[ 59%] Building CXX object CMakeFiles/litehtml.dir/src/html.cpp.o
[ 61%] Building CXX object CMakeFiles/litehtml.dir/src/html_tag.cpp.o
[ 63%] Building CXX object CMakeFiles/litehtml.dir/src/iterators.cpp.o
[ 65%] Building CXX object CMakeFiles/litehtml.dir/src/media_query.cpp.o
[ 68%] Building CXX object CMakeFiles/litehtml.dir/src/style.cpp.o
[ 70%] Building CXX object CMakeFiles/litehtml.dir/src/stylesheet.cpp.o
[ 72%] Building CXX object CMakeFiles/litehtml.dir/src/table.cpp.o
[ 74%] Building CXX object CMakeFiles/litehtml.dir/src/utf8_strings.cpp.o
[ 76%] Building CXX object CMakeFiles/litehtml.dir/src/web_color.cpp.o
[ 78%] Building C object CMakeFiles/litehtml.dir/src/gumbo/attribute.c.o
[ 80%] Building C object CMakeFiles/litehtml.dir/src/gumbo/char_ref.c.o
[ 82%] Building C object CMakeFiles/litehtml.dir/src/gumbo/error.c.o
[ 85%] Building C object CMakeFiles/litehtml.dir/src/gumbo/parser.c.o
[ 87%] Building C object CMakeFiles/litehtml.dir/src/gumbo/string_buffer.c.o
[ 89%] Building C object CMakeFiles/litehtml.dir/src/gumbo/string_piece.c.o
[ 91%] Building C object CMakeFiles/litehtml.dir/src/gumbo/tag.c.o
[ 93%] Building C object CMakeFiles/litehtml.dir/src/gumbo/tokenizer.c.o
[ 95%] Building C object CMakeFiles/litehtml.dir/src/gumbo/utf8.c.o
[ 97%] Building C object CMakeFiles/litehtml.dir/src/gumbo/util.c.o
[100%] Building C object CMakeFiles/litehtml.dir/src/gumbo/vector.c.o
Linking CXX static library liblitehtml.a
[100%] Built target litehtml
$`

Here is the output for cmake and make commands.

**Comment by tordex** [comment]
litehtml is the **library**. If you want executable try the simple browsers based on litehtml:
For Windows: https://github.com/litehtml/litebrowser
For Linux: https://github.com/litehtml/litebrowser-linux
