### ISSUE TITLE
'box' class is missing virtual dtor declaration

### ISSUE THREAD

**Issue by mpdaly** [litehtml/litehtml#75]
The `box` class is missing a virtual destructor declaration. There are several classes derived from `box`, and, because of the missing declaration, these are not destroyed correctly when used via `box::ptr`, and thus leak memory.

Adding this line is enough to solve the problem:

`virtual ~box() {}`

**Comment by tordex** [comment]
Virtual destructor was added in commit 583c7e3fee62f8b9794581367c1782542c74e7c6

**Comment by mpdaly** [comment]
Sorry, missed that completely: I'm using source from 3 days before the commit! Are there any plans for another release (0.4 is > 3 years old, and 100+ commits behind master)?
