### ISSUE TITLE
Bug in margin / padding with position: absolute

### ISSUE THREAD

**Issue by josecpujol** [litehtml/litehtml#79]
The following code produces a margin that is twice what is was set:
```` 
<!DOCTYPE html>
<html>
<head>
<style>
div {
  position: absolute;
  width: 100px;
  height: 100px;
  margin-left: 100px;
  background-color: red;
}
</style>
</head>
<body>

<div></div>

</body>
</html>
````
It only happens with `position: absolute` and when `left` is not set

Please see the difference between litebrowser (top) and chrome (bottow), that properly displays the 100px margin

![image](https://user-images.githubusercontent.com/6614762/51734397-46872f00-2039-11e9-9c23-7465dabc8a74.png)

**Comment by tordex** [comment]
Fixed in 6935de2
