### ISSUE TITLE
VS project does not build

### ISSUE THREAD

**Issue by mmanyen** [litehtml/litehtml#87]
c1xx : fatal error C1083: Cannot open source file: 'instream.cpp': No such file or directory
c1xx : fatal error C1083: Cannot open source file: 'xh_scanner.cpp': No such file or directory

Ideas?

**Comment by tordex** [comment]
Please don't use litehtml.vcproj the right project file is litehtml.vcxproj.
litehtml.vcproj should be removed

**Comment by mmanyen** [comment]
Thanks for the reply, it builds now.
