### ISSUE TITLE
Text vertical position does not advance

### ISSUE THREAD

**Issue by mmanyen** [litehtml/litehtml#88]
Maybe this is too vague, but I am just starting out with your library and I have the first drawing happening. The problem is that the text does not move downward on -br-

After filling out the text parts of the container, here is the init I use...
```
   litehtml::document_container* pContainer = new litehtml::my_container();
   litehtml::context ctx;
   ctx.load_master_stylesheet(masterCSS);
   mDoc = litehtml::document::createFromUTF8("<big>Hello<br>Next Line<br></big>", pContainer, &ctx, NULL);
```
"Hello" and "Next Line" are both at the same y coordinate, while the x coordinate is set back to the left of the window (correctly).

Any Ideas you have would be most welcome...

**Comment by tordex** [comment]
Check implementation of function ``litehtml::my_container::create_font`` the last parameter ``litehtml::font_metrics* fm`` must be initialized correctly. See the example in ``containers\cairo\cairo_container.cpp``:
```
		fm->ascent		= fnt->metrics().ascent;
		fm->descent		= fnt->metrics().descent;
		fm->height		= fnt->metrics().height;
		fm->x_height	= fnt->metrics().x_height;
		if(italic == litehtml::fontStyleItalic || decoration)
		{
			fm->draw_spaces = true;
		} else
		{
			fm->draw_spaces = false;
		}
```
litehtml uses font_metrics to find the height of text.

**Comment by mmanyen** [comment]
Here is the code you reference... Doesn't work. 
Using Windows...
```
      if (fm)
      {
         HDC dc = GetDC(NULL);
         HFONT old = (HFONT) SelectObject(dc, hFont);
         TEXTMETRIC tm;
         GetTextMetrics(dc, &tm);
         fm->ascent = tm.tmAscent;
         fm->descent = tm.tmDescent;
         fm->height = tm.tmHeight;
         fm->x_height = tm.tmHeight;
         if (italic == litehtml::fontStyleItalic || decoration)
         {
            fm->draw_spaces = true;
         }
         else
         {
            fm->draw_spaces = false;
         }
         SelectObject(dc, old);
      }
```

**Comment by tordex** [comment]
Please, can you share a simple project with your container class?

**Comment by mmanyen** [comment]
Here is the project, i left out the litehtml sources of course


[Win32Project1.zip](https://github.com/litehtml/litehtml/files/3192004/Win32Project1.zip)

**Comment by tordex** [comment]
You don't call ``document::render`` method and this is a problem. You must call ``render`` to place elements into correct positions:
``` c++
    case WM_PAINT:
        {
            PAINTSTRUCT ps;
            HDC hdc = BeginPaint(hWnd, &ps);
            mDoc->render(300);  // <<<<<=== add this
            mDoc->draw((litehtml::uint_ptr) hdc, 5, 55, NULL);
            // TODO: Add any drawing code that uses hdc here...
            EndPaint(hWnd, &ps);
        }
        break;
```
I take ``300`` as parameter for example only. Usually this is the window width. After rendering you can use ``mDoc->height()`` to find the document height.
BTW, this is described in [wiki](https://github.com/litehtml/litehtml/wiki/How-to-use-litehtml)

**Comment by mmanyen** [comment]
This works, Thank you very much.

**Comment by tordex** [comment]
Where the crash appears in source?

**Comment by mmanyen** [comment]
It exits without being caught by the debugger. I do think it is a VS2019 issue because when used with VS2015 it is fine.
