### ISSUE TITLE
viewing eBay html mail causes issues

### ISSUE THREAD

**Issue by Tharn** [litehtml/litehtml#98]
Viewing a html email from eBay causes the following issue with text formatting:

![ebay](https://user-images.githubusercontent.com/13466852/64007232-0f6b8580-cb14-11e9-9e51-32f44d9f19f0.png)

This occurs both with the liteHTML Claws Mail plugin and the litebrowser standalone, so it shouldn't be a Claws issue. I also confirmed similar overlapping text from other senders, but eBay should be easiest to reproduce.

**Comment by tordex** [comment]
Could you attach the email source or html?

**Comment by tordex** [comment]
Tried to open the file you've sent me by email in the lite browser. I don't see overlapping text.
I'll try to investigate liteHTML Claws Mail plugin sources.
