### ISSUE TITLE
Wrong element position with double "float: right"

### ISSUE THREAD

**Issue by e4z9** [litehtml/litehtml#99]
The HTML that I have leads to overlapping text in litehtml because part of the text is shown on the left instead of the right side.
Minimal example of the part that should be on the right side, but doesn't work correctly:

```html
<html>
<body>
    <table style="float: right">
      <tr>
        <td style="float: right" width="100%">Should be on right side</td>
      </tr>
    </table>
</body>
</html>
```

**Comment by tordex** [comment]
This issue is fixed
